package:
  name: pyaisa
  version: "0.8.5"

build:
  number: 3
  script_env:
    - CC # [not win]
    - CXX # [not win]

source:
  path: ..

requirements:
  build:
    - python
    - numpy {{NPY_VER}}*
    - requests
    - swig # [not win]
    - pytest
  run:
    - python
    - numpy {{NPY_VER}}*
    - pytest

about:
  license: MIT License
  home: https://github.com/newlawrence/Pysapp
  summary: "ISA Model computed in C++"
