package: pyaisa
script:
  - conda build conda
build_targets:
  - conda
platform: 
  - linux-64
engine:
  - python=3.3 numpy=1.9  CONDA_PY=33 CONDA_NPY=19
  - python=3.4 numpy=1.9  CONDA_PY=34 CONDA_NPY=19
  - python=3.4 numpy=1.10 CONDA_PY=34 CONDA_NPY=110
  - python=3.5 numpy=1.9  CONDA_PY=35 CONDA_NPY=19
  - python=3.5 numpy=1.10 CONDA_PY=35 CONDA_NPY=110
env:
  - CC=gcc
