package: pyaisa
script:
  - conda build conda
build_targets:
  - conda
platform: 
  - linux-64
engine:
  - python=3.3 numpy=1.7
  - python=3.3 numpy=1.8
  - python=3.3 numpy=1.9
  - python=3.4 numpy=1.8
  - python=3.4 numpy=1.9
  - python=3.4 numpy=1.10
  - python=3.5 numpy=1.9
  - python=3.5 numpy=1.10
env:
  - CC=gcc
