package: pysapp
script:
  - conda build ./scripts/condarecipe
build_targets:
  - conda
platform: 
  - linux-64
engine:
  - python=3.1
  - python=3.2
  - python=3.3
  - python=3.4 numpy=1.8
  - python=3.4 numpy=1.9
env:
  - CC=gcc
