package: pyaisa
platform: 
  - linux-64
engine:
  - python=3.5
env:
  - NUMPY=1.9
  - NUMPY=1.10
build_targets:
  - conda
script:
  - conda update conda-build
  - CC=gcc CXX=g++ conda build recipe --numpy $NUMPY --quiet
