package: pyaisa
script:
  - export CONDA_PY=$(python -c "from sys import version_info as ver;print(str(ver.major) + str(ver.minor))")
  - export CONDA_NPY=$(python -c "import numpy;npver=numpy.__version__;print(npver[:npver.rfind('.')].replace('.',''))")
  - conda build recipe
build_targets:
  - conda
platform: 
  - linux-64
engine:
  - python=3.5 numpy=1.9
  - python=3.5 numpy=1.10
env:
  - CC=gcc
