package: pyaisa
script:
  - export NPVER=$(python -c "import numpy;print(numpy.__version__)")
  - conda build --numpy $NPVER conda
build_targets:
  - conda
platform: 
  - linux-64
engine:
  - python=3.3 numpy=1.9
  - python=3.4 numpy=1.9
  - python=3.4 numpy=1.10
  - python=3.5 numpy=1.9
  - python=3.5 numpy=1.10
env:
  - CC=gcc
