language: objective-c

env:
  matrix:
    - python=3.3 CONDA_PY=33 CONDA_NPY=19
    - python=3.4 CONDA_PY=34 CONDA_NPY=19

  global:
    - secure: "jqJ5q8nVDeUm/yj0Co41/YCrW9wkhhsbr5ZeqOBT1/tWzrMUYoKKrA735cZAOt/F/c17uOB0OuR6pswRwLOHi2LMNKNTZYEQKgqL1gz6VHFCX8n4Cp5pU1eu3x5nApdPJTJUSGCA1Q1c2RUqJXH5+M+GuD6dmDEWvaTUcUNyxbhi21Jofqm0wFcgdD4y6Qp/s3zD5WBzSc0Qsn3vbe4RQwN0oAhIfW49cUnhTyPfEing7Rf9Z5EbfmF4Xj9DqoVKes+HfgzTW3FlJ3PKYre26MxLZ3L12SavgRDd4SqEuQ/l9wY+6ezxmZh7RahbA2ilxBgcnGHs6kCEOnAtk2nJd5j0DqAPIovyIl9DQUUknf1ycJFFUAgpaKMmBwo7E46ye5Mc+Tbueln3UPB+sikePpkUw1el1w5dkNUU9dfrIM39tBDZeXalRi1gl14uIfcbh+GrXGv6kS6D7v4N+bn7D9HCxOPZJFJHu7aYuQsA8peZnrV2aFCWDiNKSJNKH9BuSd0UWwcraWU8JlDNZdiE5flG3+jY4c/rUApy1m6EfwenOn4H81UK5O94xOxbHl7RtRcszrdqsEVgvY7L5Y2PhmgC4npcrWUHPs+f8hT4VgZ3AXdciugC7fDCPvTTxeNV9LQh9+GQNAHMuoU6ZrBxbb9c4Dv2+GWdjauYcdOiE68="

install:
  - source integration/travis/install.sh

script:
  - conda build recipes/conda-unix --quiet

after_success:
  - python integration/binstar-push.py recipes/conda-unix releases
