package:
  name: pyaisa
  version: "0.8.5"

build:
  number: 2
  string: np{{ np }}py{{ py }}
  script_env:
    - BINSTAR_BUILD     # [not win]
    - TRAVIS_BUILD_ID   # [not win]
    - APPVEYOR_BUILD_ID # [not win]

source:
  path: ..

requirements:
  build:
    - python
    - numpy 1.7*  # [np == 17]
    - numpy 1.8*  # [np == 18]
    - numpy 1.9*  # [np == 19]
    - numpy 1.10* # [np == 110]
    - requests
    - swig        # [not win]
    - pytest
  run:
    - python
    - numpy 1.7*  # [np == 17]
    - numpy 1.8*  # [np == 18]
    - numpy 1.9*  # [np == 19]
    - numpy 1.10* # [np == 110]
    - pytest

about:
  license: MIT License
  home: https://github.com/newlawrence/Pysapp
  summary: "ISA Model computed in C++"
