package:
  name: pyaisa
  version: "0.8.5"

build:
  number: 1
  script_env:
    - BINSTAR_BUILD # [not win]
    - TRAVIS_BUILD_ID # [not win]
    - APPVEYOR_BUILD_ID # [not win]

source:
  path: ..

requirements:
  build:
    - python
    - numpy
    - swig # [not win]
    - pytest
  run:
    - python
    - numpy
    - pytest

about:
  license: MIT License
  home: https://github.com/newlawrence/Pysapp
  summary: "ISA Model computed in C++"
