package:
  name: pysapp
  version: "0.8.3"

source:
  path: ../..
  #git_url: https://github.com/newlawrence/Pysapp.git

build:
  number: 2

requirements:
  build:
    - python
    - numpy
    - swig
    - pytest
  run:
    - python >=3.4
    - numpy >=1.8
    - pytest

about:
  license: MIT License
  home: https://github.com/newlawrence/Pysapp
  summary: "ISA Model computed in C++"
