package:
  name: pysapp
  version: "0.8.4"

build:
  number: 1

source:
  path: ../..

requirements:
  build:
    - python
    - numpy
    - swig
    - pytest
  run:
    - python
    - numpy
    - pytest

about:
  license: MIT License
  home: https://github.com/newlawrence/Pysapp
  summary: "ISA Model computed in C++"
